# Generated by Django 3.2.25 on 2025-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('template_name', models.CharField(help_text='Nombre del archivo de template (sin .html)', max_length=100)),
            ],
        ),
    ]
